{{- if and .Values.auth.enabled .Values.auth.podDisruptionBudget -}}
{{- $name := include "buzzfeed-sso.name" . -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "buzzfeed-sso.fullname" . }}-auth
  labels:
    app: {{ $name }}
    chart: {{ template "buzzfeed-sso.chart" . }}
    component: {{ $name }}-auth
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- toYaml .Values.auth.podDisruptionBudget | nindent 2 }}
  selector:
    matchLabels:
      app: {{ $name }}
      component: {{ $name }}-auth
      release: {{ .Release.Name }}
{{- end }}
