{{- if and .Values.proxy.enabled .Values.proxy.podDisruptionBudget -}}
{{- $name := include "buzzfeed-sso.name" . -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "buzzfeed-sso.fullname" . }}-proxy
  labels:
    app: {{ $name }}
    chart: {{ template "buzzfeed-sso.chart" . }}
    component: {{ $name }}-proxy
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- toYaml .Values.proxy.podDisruptionBudget | nindent 2 }}
  selector:
    matchLabels:
      app: {{ $name }}
      component: {{ $name }}-proxy
      release: {{ .Release.Name }}
{{- end }}
